name: Ejecutar pruebas

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configurar Node.js y Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Instalar dependencias
        run: yarn install
      - name: Compilar TypeScript
        run: yarn build
      - name: Ejecutar pruebas
        run: yarn test
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
